Fix compilter error: redefinition of typedef
Old GCC compilers treat multiple typedefs of same type as error,
AgAccount & AgManager are defined in common place ag-types.h,